"""
Analysis 3: Layer-wise Saliency Analysis

Requires per-layer npy files generated by:
  python demo_step2_llava.py --model-path ... --save-layers

For each available sample+mode, loads the 32 per-layer saliency matrices
(head-averaged, produced inside the layer loop in demo_step2_llava.py) and
computes one scalar score per layer.

Groups layers into three functional stages:
  Early  : layers  0-10  (low-level syntax / local context)
  Middle : layers 11-21  (semantic composition)
  Late   : layers 22-31  (task-specific reasoning / output)

Supports both:
  - Single sample, single mode  (e.g., only 499775 hall)  → shows layer profile
  - Multiple samples, hall+real → adds hall vs real comparison
"""

import numpy as np
import matplotlib.pyplot as plt
import os
from scipy import stats

NPY_DIR = '/work/users/z/h/zhenqi/LVLMs-Saliency/npy'
FIG_DIR = '/work/users/z/h/zhenqi/LVLMs-Saliency/figures'
RES_DIR = '/work/users/z/h/zhenqi/LVLMs-Saliency/results'

N_LAYERS = 32
LAYER_GROUPS = {
    'Early (0-10)':   list(range(0, 11)),
    'Middle (11-21)': list(range(11, 22)),
    'Late (22-31)':   list(range(22, 32)),
}
GROUP_COLORS = ['#e8f4f8', '#fff3e0', '#f3e8ff']

# Preferred order to search for samples
PREFERRED_SAMPLES = ['541223', '296775', '428231',   # Case A/B/C
                     '499775', '011987', '124952',
                     '137612', '279774', '406451',
                     '521509']


# ── Helpers ───────────────────────────────────────────────────────────────────

def layer_score(mat):
    """
    Scalar saliency score for one layer matrix.
    Mean of the bottom-quarter rows (last generated tokens),
    ignoring near-zero background pixels.
    """
    n = mat.shape[0]
    bottom = mat[max(0, n * 3 // 4):, :]
    vals = bottom[bottom > 0.01]
    return float(np.mean(vals)) if len(vals) > 0 else 0.0


def load_layer_profile(hmode, name):
    """
    Load all 32 per-layer saliency npy files for one sample+mode.
    Returns array [32] or None if files are missing.
    """
    scores = []
    for l in range(N_LAYERS):
        path = os.path.join(NPY_DIR,
                            f'onlytext_{hmode}_{name}_layer{l:02d}_saliency.npy')
        if not os.path.exists(path):
            return None
        scores.append(layer_score(np.load(path)))
    return np.array(scores)


def discover_data():
    """Scan NPY_DIR for available per-layer files and return structured dict."""
    data = {}   # data[name][hmode] = np.array[32]
    if not os.path.exists(NPY_DIR):
        return data
    for name in PREFERRED_SAMPLES:
        for hmode in ['hall', 'real']:
            profile = load_layer_profile(hmode, name)
            if profile is not None:
                data.setdefault(name, {})[hmode] = profile
    return data


# ── Plotting ──────────────────────────────────────────────────────────────────

def shade_groups(ax):
    boundaries = [0, 11, 22, 32]
    for i, (lo, hi) in enumerate(zip(boundaries[:-1], boundaries[1:])):
        ax.axvspan(lo - 0.5, hi - 0.5, alpha=0.12, color=GROUP_COLORS[i], zorder=0)
    for b in boundaries[1:-1]:
        ax.axvline(b - 0.5, color='gray', lw=0.8, ls='--', alpha=0.5)


def label_groups(ax, y_frac=0.97):
    labels = ['Early', 'Middle', 'Late']
    midpoints = [5, 16, 26]
    ylim = ax.get_ylim()
    y = ylim[0] + y_frac * (ylim[1] - ylim[0])
    for mid, label in zip(midpoints, labels):
        ax.text(mid, y, label, ha='center', va='top',
                fontsize=8, color='#555555')


# ── Main ──────────────────────────────────────────────────────────────────────

def run():
    print('=== Analysis 3: Layer-wise Saliency Analysis ===\n')

    data = discover_data()
    layers = np.arange(N_LAYERS)

    if not data:
        print('No per-layer npy files found in:', NPY_DIR)
        print()
        print('Steps to generate them:')
        print('  1. On Colab, run Cells 10-12 in colab_setup.ipynb')
        print('     (re-runs demo_step2_llava.py --save-layers for 499775 hall mode)')
        print('  2. Download the 32 npy files from Colab')
        print('  3. Upload to:', NPY_DIR)
        print('  4. Re-run this script')
        return

    print(f'Found per-layer data for:')
    for name, modes in data.items():
        print(f'  Sample {name}: modes = {list(modes.keys())}')

    os.makedirs(FIG_DIR, exist_ok=True)
    os.makedirs(RES_DIR, exist_ok=True)

    # ── Case 1: hall vs real comparison (need both modes for ≥1 sample) ───────
    paired = {n: m for n, m in data.items() if 'hall' in m and 'real' in m}

    if paired:
        hall_arr = np.array([paired[n]['hall'] for n in paired])
        real_arr = np.array([paired[n]['real'] for n in paired])
        hall_mean = hall_arr.mean(axis=0)
        real_mean = real_arr.mean(axis=0)

        print(f'\nPaired hall+real comparison (n={len(paired)} samples):')
        print(f'{"Group":<22} {"Hall":>8} {"Real":>8} {"Gap":>10}')
        print('-' * 52)
        for gname, ids in LAYER_GROUPS.items():
            h = hall_mean[ids].mean()
            r = real_mean[ids].mean()
            print(f'{gname:<22} {h:>8.4f} {r:>8.4f} {r-h:>+10.4f}')

        _plot_comparison(layers, hall_arr, real_arr, list(paired.keys()))

    # ── Case 2: single-mode profiles ──────────────────────────────────────────
    print('\nPer-sample, per-mode layer profiles:')
    all_profiles = {}
    for name, modes in data.items():
        for hmode, profile in modes.items():
            all_profiles[(name, hmode)] = profile
            print(f'  {name} ({hmode}):  '
                  f'early={profile[:11].mean():.4f}  '
                  f'mid={profile[11:22].mean():.4f}  '
                  f'late={profile[22:].mean():.4f}')

    _plot_profiles(layers, all_profiles)
    _save_summary(layers, all_profiles, paired)
    print('\nDone.')


def _plot_comparison(layers, hall_arr, real_arr, sample_names):
    """Hall vs real side-by-side: mean curve + gap bar."""
    hall_mean = hall_arr.mean(axis=0)
    real_mean = real_arr.mean(axis=0)
    gap = real_mean - hall_mean

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle(
        f'Layer-wise Saliency: Hallucinated vs Correct  (n={len(sample_names)} samples)',
        fontsize=13, fontweight='bold'
    )
    colors = {'hall': '#d62728', 'real': '#1f77b4'}

    # Left: mean curves
    ax = axes[0]
    shade_groups(ax)
    ax.plot(layers, real_mean, 'o-', color=colors['real'], lw=2, ms=4, label='Correct (real)')
    ax.plot(layers, hall_mean, 's--', color=colors['hall'], lw=2, ms=4, label='Hallucinated')
    if hall_arr.shape[0] > 1:
        ax.fill_between(layers, hall_arr.mean(0)-hall_arr.std(0),
                        hall_arr.mean(0)+hall_arr.std(0), color=colors['hall'], alpha=0.12)
        ax.fill_between(layers, real_arr.mean(0)-real_arr.std(0),
                        real_arr.mean(0)+real_arr.std(0), color=colors['real'], alpha=0.12)
    label_groups(ax)
    ax.set_xlabel('Transformer Layer Index')
    ax.set_ylabel('Mean Saliency Score')
    ax.set_title('Saliency (|Attn × Grad|) per Layer')
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)
    ax.set_xlim(-0.5, 31.5)

    # Right: gap bar
    ax2 = axes[1]
    shade_groups(ax2)
    bar_colors = ['#2ca02c' if g >= 0 else '#d62728' for g in gap]
    ax2.bar(layers, gap, color=bar_colors, alpha=0.75)
    ax2.axhline(0, color='black', lw=0.8)
    label_groups(ax2)
    ax2.set_xlabel('Transformer Layer Index')
    ax2.set_ylabel('Gap  (real − hall)')
    ax2.set_title('Per-Layer Gap (real − hall)\nGreen = correct > hallucinated')
    ax2.grid(axis='y', alpha=0.3)
    ax2.set_xlim(-0.5, 31.5)

    plt.tight_layout()
    out = os.path.join(FIG_DIR, 'layer_analysis_comparison.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    print(f'Saved: {out}')
    plt.close()


def _plot_profiles(layers, all_profiles):
    """One curve per (sample, mode) — useful even with a single sample."""
    if not all_profiles:
        return

    colors_by_mode = {'hall': '#d62728', 'real': '#1f77b4', 'unknown': '#7f7f7f'}
    fig, ax = plt.subplots(figsize=(12, 5))
    shade_groups(ax)

    for (name, hmode), profile in all_profiles.items():
        color = colors_by_mode.get(hmode, '#7f7f7f')
        ls = '--' if hmode == 'hall' else '-'
        marker = 's' if hmode == 'hall' else 'o'
        label = f'{name} ({hmode})'
        ax.plot(layers, profile, ls, color=color, lw=1.5, ms=3,
                marker=marker, label=label, alpha=0.85)

    label_groups(ax)
    ax.set_xlabel('Transformer Layer Index')
    ax.set_ylabel('Mean Saliency Score')
    ax.set_title('Per-Layer Saliency Profile by Sample and Mode')
    ax.legend(fontsize=8, loc='upper right')
    ax.grid(alpha=0.3)
    ax.set_xlim(-0.5, 31.5)

    plt.tight_layout()
    out = os.path.join(FIG_DIR, 'layer_analysis_profiles.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    print(f'Saved: {out}')
    plt.close()


def _save_summary(layers, all_profiles, paired):
    lines = ['=== Analysis 3: Layer-wise Saliency Analysis ===\n\n']

    lines.append('Per-sample/mode layer-group means:\n')
    for (name, hmode), profile in all_profiles.items():
        lines.append(f'  {name} ({hmode}):\n')
        for gname, ids in LAYER_GROUPS.items():
            lines.append(f'    {gname}: {profile[ids].mean():.4f}\n')

    if paired:
        hall_arr = np.array([paired[n]['hall'] for n in paired])
        real_arr = np.array([paired[n]['real'] for n in paired])
        hall_mean = hall_arr.mean(0)
        real_mean = real_arr.mean(0)
        lines.append(f'\nHall vs Real (n={len(paired)}):\n')
        for gname, ids in LAYER_GROUPS.items():
            h = hall_mean[ids].mean()
            r = real_mean[ids].mean()
            lines.append(f'  {gname}: hall={h:.4f} real={r:.4f} gap={r-h:+.4f}\n')

    path = os.path.join(RES_DIR, 'layer_analysis_summary.txt')
    with open(path, 'w') as f:
        f.writelines(lines)
    print(f'Saved: {path}')


if __name__ == '__main__':
    run()
